import { StyleSheet } from "react-native";
import {
  BORDER_RADIUS,
  COLORS,
  FONT_SIZE,
  FONT_WEIGHT,
  SPACING,
} from "../../styles/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundLight,
  },
  scrollContent: {
    padding: SPACING.xl,
    paddingBottom: SPACING.xl,
    marginTop: SPACING.lg,
  },
  header: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.extraBold,
    color: COLORS.primaryDark,
    marginBottom: SPACING.sm,
  },
  subtitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.primaryMedium,
    marginBottom: SPACING.xl,
    lineHeight: 22,
  },
  label: {
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.primaryDarker,
    marginBottom: SPACING.xs,
  },
  input: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: BORDER_RADIUS.md,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    fontSize: FONT_SIZE.md,
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.bold,
    backgroundColor: COLORS.white,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  switchRowActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.backgroundVeryLight,
  },
  switchLabelBox: {
    flex: 1,
  },
  switchText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.primaryDarker,
    fontWeight: FONT_WEIGHT.bold,
  },
  switchHint: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.primaryMedium,
    marginTop: 2,
  },
  switchTrack: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.borderLight,
    padding: 2,
    justifyContent: "center",
  },
  switchTrackActive: {
    backgroundColor: COLORS.primary,
    alignItems: "flex-end",
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.white,
  },
  switchThumbActive: {
    backgroundColor: COLORS.white,
  },
  photoUploadCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  photoUploadIconBox: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: COLORS.backgroundVeryLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SPACING.sm,
  },
  photoUploadTextBox: {
    flex: 1,
  },
  photoUploadTitle: {
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primaryDark,
  },
  photoUploadSubtitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.primaryMedium,
    marginTop: 2,
  },
  photoPreview: {
    width: "100%",
    height: 180,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.backgroundVeryLight,
    marginBottom: SPACING.md,
    justifyContent: "center",
    alignItems: "center",
  },
  photosGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  photoCard: {
    width: "48%",
    height: 120,
    borderRadius: BORDER_RADIUS.lg,
    overflow: "hidden",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.borderVeryLight,
  },
  photoPlaceholder: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.primaryMedium,
  },
  photoImage: {
    width: "100%",
    height: "100%",
    borderRadius: BORDER_RADIUS.lg,
  },
  button: {
    height: 52,
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    marginTop: SPACING.sm,
  },
  buttonText: {
    color: COLORS.white,
    fontWeight: FONT_WEIGHT.bold,
    fontSize: FONT_SIZE.md,
  },
  textButton: {
    marginTop: SPACING.md,
    alignSelf: "center",
  },
  textButtonText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.bold,
  },
});

export default { styles };
